name = "ElementalBalancing"
uuid = "7cb4c9bd-6df1-4691-8f58-6e233c74ed41"
authors = ["Fabian Müller"]
version = "1.0.0-DEV"

[deps]
BioprocessKinetics = "ca03edca-702a-487a-9f32-b26b17538018"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
